# Generated by Django 5.2.3 on 2025-08-05 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, related_name='rsvp_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
