# Generated by Django 5.2.3 on 2025-06-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
