# Generated by Django 5.2.3 on 2025-06-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_rename_email_participant_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='user_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='participant',
            name='hudai',
            field=models.CharField(default='sdfsdf', max_length=100),
        ),
    ]
