# Generated by Django 5.2.3 on 2025-06-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_rename_user_email_participant_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='email',
            new_name='user_email',
        ),
    ]
