# Generated by Django 5.2.3 on 2025-06-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_rename_email_participant_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='hudai',
        ),
        migrations.AlterField(
            model_name='participant',
            name='user_email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
