# Generated by Django 5.2.3 on 2025-06-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0009_remove_participant_hudai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
