# Generated by Django 5.2.3 on 2025-06-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0010_alter_participant_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
    ]
