# Generated by Django 5.2.3 on 2025-07-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0014_event_participant_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
