# Generated by Django 5.2.3 on 2025-07-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0016_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='event_images/default_event.jpg', upload_to='event_images'),
        ),
    ]
