# Generated by Django 5.2.3 on 2025-07-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0017_alter_event_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='category_description',
        ),
    ]
