# Generated by Django 5.2.3 on 2025-08-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
