# Generated by Django 5.2.3 on 2025-08-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_custom_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
