# Generated by Django 5.2.3 on 2025-08-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_custom_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', upload_to='profile_images'),
        ),
    ]
